In [2]:
import pandas
import openpyxl
import xlrd

print("Pandas:", pandas.__version__)
print("OpenPyXL:", openpyxl.__version__)
print("xlrd:", xlrd.__version__)

ModuleNotFoundError: No module named 'openpyxl'

In [3]:
import pandas
import openpyxl
import xlrd

print("Pandas:", pandas.__version__)
print("OpenPyXL:", openpyxl.__version__)
print("xlrd:", xlrd.__version__)

ModuleNotFoundError: No module named 'openpyxl'

In [4]:
%pip install pandas openpyxl xlrd

Requirement already satisfied: pandas in c:\Users\Meghana\OneDrive\Desktop\BANKING-CREDIT-RISK\.venv\Lib\site-packages (3.0.5)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\Meghana\OneDrive\Desktop\BANKING-CREDIT-RISK\.venv\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Meghana\OneDrive\Desktop\BANKING-CREDIT-RISK\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Meghana\OneDrive\Desktop\BANKING-CREDIT-RISK\.venv\Lib\site-packages (from pandas) (2026.3)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in c:\Users\Meghana\OneDrive\Desktop\BANKING-CREDIT-RISK\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: xlrd, et-xmlfile, openpyxl

   ---------------------------------------- 0/3 [xlrd]
   ---------------------------------------- 0/3 [xlrd]
   ---------------------------------------- 0/3 [xlrd]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   ---------------------------------------- 3/3 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5 xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas
import openpyxl
import xlrd

print("Pandas:", pandas.__version__)
print("OpenPyXL:", openpyxl.__version__)
print("xlrd:", xlrd.__version__)

Pandas: 3.0.5
OpenPyXL: 3.1.5
xlrd: 2.0.2

In [6]:
import pandas as pd

In [7]:
df = pd.read_excel("../data/default of credit card clients.xls")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [8]:
df

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
1,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
2,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
3,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
4,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29996,29996,220000,1,3,1,39,0,0,0,0,...,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29997,29997,150000,1,3,2,43,-1,-1,-1,-1,...,8979,5190,0,1837,3526,8998,129,0,0,0
29998,29998,30000,1,2,2,37,4,3,2,-1,...,20878,20582,19357,0,0,22000,4200,2000,3100,1
29999,29999,80000,1,3,1,41,1,-1,0,0,...,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
30000,30000,50000,1,2,1,46,0,0,0,0,...,36535,32428,15313,2078,1800,1430,1000,1000,1000,1

In [9]:
df.head()

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
1,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
2,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
3,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
4,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0

In [11]:
print(df.shape)

(30001, 25)

In [12]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 30001
Columns: 25

In [13]:
print(df.columns.tolist())

['Unnamed: 0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23', 'Y']

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30001 entries, 0 to 30000
Data columns (total 25 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  30001 non-null  object
 1   X1          30001 non-null  object
 2   X2          30001 non-null  object
 3   X3          30001 non-null  object
 4   X4          30001 non-null  object
 5   X5          30001 non-null  object
 6   X6          30001 non-null  object
 7   X7          30001 non-null  object
 8   X8          30001 non-null  object
 9   X9          30001 non-null  object
 10  X10         30001 non-null  object
 11  X11         30001 non-null  object
 12  X12         30001 non-null  object
 13  X13         30001 non-null  object
 14  X14         30001 non-null  object
 15  X15         30001 non-null  object
 16  X16         30001 non-null  object
 17  X17         30001 non-null  object
 18  X18         30001 non-null  object
 19  X19         30001 non-null  object
 20  X20         30001 non-null  object
 21  X21         30001 non-null  object
 22  X22         30001 non-null  object
 23  X23         30001 non-null  object
 24  Y           30001 non-null  object
dtypes: object(25)
memory usage: 5.7+ MB

In [15]:
df['Y'].value_counts()

Y
0                             23364
1                              6636
default payment next month        1
Name: count, dtype: int64

In [16]:
df.isnull().sum()

Unnamed: 0    0
X1            0
X2            0
X3            0
X4            0
X5            0
X6            0
X7            0
X8            0
X9            0
X10           0
X11           0
X12           0
X13           0
X14           0
X15           0
X16           0
X17           0
X18           0
X19           0
X20           0
X21           0
X22           0
X23           0
Y             0
dtype: int64

In [18]:
print(df['Y'].value_counts())

Y
0                             23364
1                              6636
default payment next month        1
Name: count, dtype: int64

In [19]:
df.to_csv("../data/credit_default.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [20]:
df_csv = pd.read_csv("../data/credit_default.csv")

print("CSV loaded successfully!")
print("Rows:", df_csv.shape[0])
print("Columns:", df_csv.shape[1])

CSV loaded successfully!
Rows: 30001
Columns: 25

In [21]:
df = df.rename(columns={
    'X1': 'LIMIT_BAL',
    'X2': 'SEX',
    'X3': 'EDUCATION',
    'X4': 'MARRIAGE',
    'X5': 'AGE',
    'X6': 'PAY_SEPT',
    'X7': 'PAY_AUG',
    'X8': 'PAY_JUL',
    'X9': 'PAY_JUN',
    'X10': 'PAY_MAY',
    'X11': 'PAY_APR',
    'X12': 'BILL_AMT_SEPT',
    'X13': 'BILL_AMT_AUG',
    'X14': 'BILL_AMT_JUL',
    'X15': 'BILL_AMT_JUN',
    'X16': 'BILL_AMT_MAY',
    'X17': 'BILL_AMT_APR',
    'X18': 'PAY_AMT_SEPT',
    'X19': 'PAY_AMT_AUG',
    'X20': 'PAY_AMT_JUL',
    'X21': 'PAY_AMT_JUN',
    'X22': 'PAY_AMT_MAY',
    'X23': 'PAY_AMT_APR',
    'Y': 'DEFAULT'
})

df = df.drop(columns=['Unnamed: 0'])

print(df.columns.tolist())

['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_SEPT', 'PAY_AUG', 'PAY_JUL', 'PAY_JUN', 'PAY_MAY', 'PAY_APR', 'BILL_AMT_SEPT', 'BILL_AMT_AUG', 'BILL_AMT_JUL', 'BILL_AMT_JUN', 'BILL_AMT_MAY', 'BILL_AMT_APR', 'PAY_AMT_SEPT', 'PAY_AMT_AUG', 'PAY_AMT_JUL', 'PAY_AMT_JUN', 'PAY_AMT_MAY', 'PAY_AMT_APR', 'DEFAULT']

In [17]:
df['default.payment.next.month'].value_counts()

KeyError: 'default.payment.next.month'

In [22]:
df['default.payment.next.month'].value_counts()

KeyError: 'default.payment.next.month'

In [23]:
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_SEPT,PAY_AUG,PAY_JUL,PAY_JUN,PAY_MAY,...,BILL_AMT_JUN,BILL_AMT_MAY,BILL_AMT_APR,PAY_AMT_SEPT,PAY_AMT_AUG,PAY_AMT_JUL,PAY_AMT_JUN,PAY_AMT_MAY,PAY_AMT_APR,DEFAULT
0,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
1,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
2,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
3,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
4,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0

In [24]:
print(df.shape)

(30001, 24)

In [25]:
df.to_csv("../data/credit_default_clean.csv", index=False)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!

In [26]:
df_csv = pd.read_csv("../data/credit_default_clean.csv")

print("CSV loaded successfully!")
print("Rows:", df_csv.shape[0])
print("Columns:", df_csv.shape[1])

CSV loaded successfully!
Rows: 30001
Columns: 24

In [1]:
print("Jupyter notebook is working!")

Jupyter notebook is working!